#! /usr/local/bin/vvp
:ivl_version "11.0 (devel)" "(s20150603-210-g139c415)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision + 0;
:vpi_module "system";
:vpi_module "vhdl_sys";
:vpi_module "vhdl_textio";
:vpi_module "v2005_math";
:vpi_module "va_math";
:vpi_module "v2009";
S_0xab38f0 .scope module, "test" "test" 2 3;
 .timescale 0 0;
L_0xae2dc0 .functor BUFZ 1, v0xae24f0_0, C4<0>, C4<0>, C4<0>;
v0xae26e0_0 .array/port v0xae26e0, 0;
L_0xae2e30 .functor BUFZ 5, v0xae26e0_0, C4<00000>, C4<00000>, C4<00000>;
v0xae26e0_1 .array/port v0xae26e0, 1;
L_0xae2ef0 .functor BUFZ 5, v0xae26e0_1, C4<00000>, C4<00000>, C4<00000>;
v0xae2430_0 .net "clk", 0 0, L_0xae2dc0;  1 drivers
v0xae24f0_0 .var "clk_reg", 0 0;
v0xae2590 .array "r_ctrl", 0 1;
v0xae2590_0 .net v0xae2590 0, 4 0, L_0xae2e30; 1 drivers
v0xae2590_1 .net v0xae2590 1, 4 0, L_0xae2ef0; 1 drivers
v0xae26e0 .array "r_ctrl_reg", 0 1, 4 0;
v0xae27c0 .array "r_out", 0 1;
v0xae27c0_0 .net v0xae27c0 0, 31 0, L_0xae2fb0; 1 drivers
v0xae27c0_1 .net v0xae27c0 1, 31 0, L_0xae3070; 1 drivers
v0xae2920_0 .var/i "test_val", 31 0;
v0xae29c0_0 .var/i "tests", 31 0;
v0xae2aa0_0 .var "w_ctrl", 4 0;
v0xae2b90_0 .var "w_data", 31 0;
v0xae2cf0_0 .var "write", 0 0;
E_0xac6170 .event posedge, v0xa9fa90_0;
S_0xaa0400 .scope module, "uut" "register_file" 2 35, 3 25 0, S_0xab38f0;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "i_clk"
    .port_info 1 /INPUT 1 "i_write"
    .port_info 2 /INPUT 5 "i_ctrl_read1"
    .port_info 3 /OUTPUT 32 "o_read_val1"
    .port_info 4 /INPUT 5 "i_ctrl_read2"
    .port_info 5 /OUTPUT 32 "o_read_val2"
    .port_info 6 /INPUT 5 "i_ctrl_write"
    .port_info 7 /INPUT 32 "i_write_val"
v0xae1f00_0 .array/port v0xae1f00, 0;
L_0xae2fb0 .functor BUFZ 32, v0xae1f00_0, C4<00000000000000000000000000000000>, C4<00000000000000000000000000000000>, C4<00000000000000000000000000000000>;
v0xae1f00_1 .array/port v0xae1f00, 1;
L_0xae3070 .functor BUFZ 32, v0xae1f00_1, C4<00000000000000000000000000000000>, C4<00000000000000000000000000000000>, C4<00000000000000000000000000000000>;
v0xa9fa90_0 .net "i_clk", 0 0, L_0xae2dc0;  alias, 1 drivers
v0xae1980_0 .net "i_ctrl_read1", 4 0, L_0xae2e30;  alias, 1 drivers
v0xae1a60_0 .net "i_ctrl_read2", 4 0, L_0xae2ef0;  alias, 1 drivers
v0xae1b50_0 .net "i_ctrl_write", 4 0, v0xae2aa0_0;  1 drivers
v0xae1c30_0 .net "i_write", 0 0, v0xae2cf0_0;  1 drivers
v0xae1d40_0 .net "i_write_val", 31 0, v0xae2b90_0;  1 drivers
v0xae1e20_0 .var/i "k", 31 0;
v0xae1f00 .array "o_read", 0 1, 31 0;
v0xae2020_0 .net "o_read_val1", 31 0, L_0xae2fb0;  alias, 1 drivers
v0xae2190_0 .net "o_read_val2", 31 0, L_0xae3070;  alias, 1 drivers
v0xae2270 .array "registers", 0 15, 31 0;
E_0xac5f40 .event negedge, v0xa9fa90_0;
E_0xac7250 .event edge, v0xae1a60_0, v0xae1980_0, v0xa9fa90_0;
    .scope S_0xaa0400;
T_0 ;
    %pushi/vec4 0, 0, 32;
    %store/vec4 v0xae1e20_0, 0, 32;
T_0.0 ;
    %load/vec4 v0xae1e20_0;
    %cmpi/s 16, 0, 32;
    %jmp/0xz T_0.1, 5;
    %pushi/vec4 0, 0, 32;
    %ix/getv/s 4, v0xae1e20_0;
    %store/vec4a v0xae2270, 4, 0;
    %load/vec4 v0xae1e20_0;
    %addi 1, 0, 32;
    %store/vec4 v0xae1e20_0, 0, 32;
    %jmp T_0.0;
T_0.1 ;
    %end;
    .thread T_0;
    .scope S_0xaa0400;
T_1 ;
    %wait E_0xac7250;
    %load/vec4 v0xae1980_0;
    %pad/u 6;
    %ix/vec4 4;
    %load/vec4a v0xae2270, 4;
    %ix/load 4, 0, 0;
    %flag_set/imm 4, 0;
    %store/vec4a v0xae1f00, 4, 0;
    %load/vec4 v0xae1a60_0;
    %pad/u 6;
    %ix/vec4 4;
    %load/vec4a v0xae2270, 4;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %store/vec4a v0xae1f00, 4, 0;
    %jmp T_1;
    .thread T_1, $push;
    .scope S_0xaa0400;
T_2 ;
    %wait E_0xac5f40;
    %load/vec4 v0xae1c30_0;
    %pad/u 32;
    %cmpi/e 1, 0, 32;
    %jmp/0xz  T_2.0, 4;
    %load/vec4 v0xae1d40_0;
    %load/vec4 v0xae1b50_0;
    %pad/u 6;
    %ix/vec4 4;
    %store/vec4a v0xae2270, 4, 0;
T_2.0 ;
    %jmp T_2;
    .thread T_2;
    .scope S_0xab38f0;
T_3 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xae24f0_0, 0, 1;
    %end;
    .thread T_3;
    .scope S_0xab38f0;
T_4 ;
    %delay 5, 0;
    %load/vec4 v0xae24f0_0;
    %inv;
    %assign/vec4 v0xae24f0_0, 0;
    %jmp T_4;
    .thread T_4;
    .scope S_0xab38f0;
T_5 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xae2cf0_0, 0, 1;
    %end;
    .thread T_5;
    .scope S_0xab38f0;
T_6 ;
    %pushi/vec4 0, 0, 32;
    %store/vec4 v0xae29c0_0, 0, 32;
    %end;
    .thread T_6;
    .scope S_0xab38f0;
T_7 ;
    %vpi_call/w 2 23 "$dumpfile", "dump.vcd" {0 0 0};
    %vpi_call/w 2 24 "$dumpvars" {0 0 0};
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xae2cf0_0, 0, 1;
    %pushi/vec4 0, 0, 5;
    %ix/load 4, 0, 0;
    %flag_set/imm 4, 0;
    %store/vec4a v0xae26e0, 4, 0;
    %pushi/vec4 0, 0, 5;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %store/vec4a v0xae26e0, 4, 0;
    %pushi/vec4 0, 0, 32;
    %store/vec4 v0xae2b90_0, 0, 32;
    %pushi/vec4 0, 0, 5;
    %store/vec4 v0xae2aa0_0, 0, 5;
    %end;
    .thread T_7;
    .scope S_0xab38f0;
T_8 ;
    %pushi/vec4 0, 0, 32;
    %store/vec4 v0xae2920_0, 0, 32;
    %end;
    .thread T_8;
    .scope S_0xab38f0;
T_9 ;
    %wait E_0xac6170;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xae2cf0_0, 0, 1;
    %load/vec4 v0xae2aa0_0;
    %addi 1, 0, 5;
    %store/vec4 v0xae2aa0_0, 0, 5;
    %load/vec4 v0xae2b90_0;
    %addi 1, 0, 32;
    %store/vec4 v0xae2b90_0, 0, 32;
    %load/vec4 v0xae29c0_0;
    %addi 1, 0, 32;
    %store/vec4 v0xae29c0_0, 0, 32;
    %load/vec4 v0xae2aa0_0;
    %subi 1, 0, 5;
    %ix/load 4, 0, 0;
    %flag_set/imm 4, 0;
    %store/vec4a v0xae26e0, 4, 0;
    %load/vec4 v0xae2aa0_0;
    %subi 1, 0, 5;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %store/vec4a v0xae26e0, 4, 0;
    %vpi_call/w 2 46 "$display", "ctrl0 = %d out0 = %d, ctrl1 = %d out1 = %d", v0xae2590_0, v0xae27c0_0, v0xae2590_1, v0xae27c0_1 {0 0 0};
    %load/vec4 v0xae29c0_0;
    %addi 1, 0, 32;
    %cmpi/s 16, 0, 32;
    %flag_inv 5; GE is !LT
    %jmp/0xz  T_9.0, 5;
    %delay 20, 0;
    %vpi_call/w 2 48 "$finish" {0 0 0};
T_9.0 ;
    %jmp T_9;
    .thread T_9;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "register_file.test.v";
    "./register_file.v";
